version: '2.4'

services:
  movie_service:
    image: mindrelay/movie-service:${GIT_COMMIT}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      movie_db:
        condition: service_healthy

  movie_db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=movie_db_username
      - POSTGRES_PASSWORD=movie_db_password
      - POSTGRES_DB=movie_db_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_db_username -d movie_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  cast_service:
    image: mindrelay/cast-service:${GIT_COMMIT}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    depends_on:
      cast_db:
        condition: service_healthy

  cast_db:
    image: postgres:12.1-alpine
    environment:
      - POSTGRES_USER=cast_db_username
      - POSTGRES_PASSWORD=cast_db_password
      - POSTGRES_DB=cast_db_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cast_db_username -d cast_db_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ../nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cast_service
      - movie_service

  curl:
    image: curlimages/curl:8.18.0
    entrypoint: ["sh", "-lc"]
    depends_on:
      - nginx
