apiVersion: v1
kind: Service
metadata:
  name: cast-service-db
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      protocol: TCP
      name: postgres
  selector:
    app: cast-service-db
